// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWsXJ6TKIQI5jz6g3x9uN6-OJeEWYbZg8',
    appId: '1:516955679231:web:b590081281146a5e959fca',
    messagingSenderId: '516955679231',
    projectId: 'fir-xflutterxauth-ea143',
    authDomain: 'fir-xflutterxauth-ea143.firebaseapp.com',
    storageBucket: 'fir-xflutterxauth-ea143.firebasestorage.app',
    measurementId: 'G-1H3CS1NMW5',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQb7A7Y72WVTFULDR_x4GOakYxdIc11bs',
    appId: '1:516955679231:android:51082ea7ac63cf3a959fca',
    messagingSenderId: '516955679231',
    projectId: 'fir-xflutterxauth-ea143',
    storageBucket: 'fir-xflutterxauth-ea143.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPt6yul9BWRtigZ7RwoHqstpnua6hk7M',
    appId: '1:516955679231:ios:a82428ebe100a9e9959fca',
    messagingSenderId: '516955679231',
    projectId: 'fir-xflutterxauth-ea143',
    storageBucket: 'fir-xflutterxauth-ea143.firebasestorage.app',
    iosBundleId: 'com.example.konversiSuhuFlutter',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPt6yul9BWRtigZ7RwoHqstpnua6hk7M',
    appId: '1:516955679231:ios:a82428ebe100a9e9959fca',
    messagingSenderId: '516955679231',
    projectId: 'fir-xflutterxauth-ea143',
    storageBucket: 'fir-xflutterxauth-ea143.firebasestorage.app',
    iosBundleId: 'com.example.konversiSuhuFlutter',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWsXJ6TKIQI5jz6g3x9uN6-OJeEWYbZg8',
    appId: '1:516955679231:web:2cf8e96aa8286988959fca',
    messagingSenderId: '516955679231',
    projectId: 'fir-xflutterxauth-ea143',
    authDomain: 'fir-xflutterxauth-ea143.firebaseapp.com',
    storageBucket: 'fir-xflutterxauth-ea143.firebasestorage.app',
    measurementId: 'G-971XPHMNM0',
  );
}
